### ISSUE TITLE
The same model failed today, but worked before

### ISSUE THREAD

**Issue by BaohaoLiao** [facebookresearch/dynalab#101]
Hi, 

the submission system is much informed than before, since it returns the error by email. However, it also confused me for these non-detailed information. 

I obtain "Error in docker build"  for my submission https://dynabench.org/models/268 and "Exception in fetching model folder and loading config" for my submission https://dynabench.org/models/267. However, both models worked before, like https://dynabench.org/models/244. I didn't do any modification, except for changing the model.pt to a newly generated one. Could you check what's wrong with my submissions? 

By the way, is it possible to not count failed submission? Otherwise, 3 submissions as the limit are not enough, if error happens, even though it works in our local machines.

**Comment by mazhiyi** [comment]
Sounds like a bug on our side. Will look into it.

**Comment by mazhiyi** [comment]
@BaohaoLiao can you please the ids of the models that failed? I'll resubmit the build jobs for you.

**Comment by BaohaoLiao** [comment]
> @BaohaoLiao can you please confirm the ids of the models that failed? I'll resubmit the build jobs for you.

@mazhiyi you can help me to resubmit https://dynabench.org/models/267, the name is task2-615m. Thank you very much

**Comment by mazhiyi** [comment]
@BaohaoLiao 267 is being rebuilt now. I'll close this issue. Please reopen if the problem remains. Thanks!

**Comment by mazhiyi** [comment]
Underlying issue is torch-model-archiver failed to delete tmp files. Relevant PR https://github.com/pytorch/serve/pull/1016
