### ISSUE TITLE
Submit models with own extensions to fairseq

### ISSUE THREAD

**Issue by dannigt** [facebookresearch/dynalab#105]
Hi,

For Flores, we trained some models with our own extensions to fairseq. They were implemented in a fork of fairseq under the examples folder ([example](https://github.com/dannigt/fairseq/tree/master/examples/adapter_transformer/adapter_transformer_src)).

Could you advise on the best way to submit these models?

With the deadline approaching, I thought it might be better to get some suggestions instead of fiddling with things on myself. Thanks in advance for your help!

Best,
Danni

**Comment by mazhiyi** [comment]
@dannigt There are several way to do this 
1. You can pull the branch locally and in your requirements file, write `-e ./fairseq` (Note you need to specify the relative path in order for pip to search the local path)
2. option 1 is also doable if you specify the github path `git+git://github.com/`. Editable probably won't work here. 
3. If all your code is actually inside fairseq (i.e. you are going to submit as the `fairseq` folder), you can use the `--run-setup` option, which will basically run `pip install -e .` to install your folder as a library. To do this, you can run `dynalab-cli init -n <name> --amend` and set the `setup` attribute to `true`.
