### ISSUE TITLE
Successfully evaluated on dev set but failed on devtest set

### ISSUE THREAD

**Issue by BaohaoLiao** [facebookresearch/dynalab#107]
Hi,

I submit a model to small track 2 (https://www.dynabench.org/models/320). The model is successfully evaluated on dev set, but failed on devtest set. I.e. I can see the score for dev set but no score for devtest set. And the model is in "takendown".  What could be the reason?

**Comment by gwenzek** [comment]
I think your model is a bit too slow.
It passed on the dev set but failed on the devtest. Can you try again with a larger batch size ? You are currently using 32.

**Comment by BaohaoLiao** [comment]
> I think your model is a bit too slow.
> It passed on the dev set but failed on the devtest. Can you try again with a larger batch size ? You are currently using 32.

I increase the batch size and it works. Thank you very much.
