### ISSUE TITLE
Question about the dockerfile

### ISSUE THREAD

**Issue by sbsyangjian** [facebookresearch/dynalab#77]
When I execute the cmd "dynalabcli test -n <name_of_your_model>". The docker build fails and I notice that the 
WORKDIR /home/model-server/code
RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e code; fi.
The error reports can not find the code.
I think the "RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e code; fi." should be "RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e .; fi." since we have "WORKDIR /home/model-server/code"  ?

**Comment by TristanThrush** [comment]
Hey @sbsyangjian, could you send me:
- the exact command that you are using
- what the terminal outputs
- your setup_config.json (this should be in .dynalab/<name of your model>)
- the ts_log.log (this should be in .dynalab/<name of your model>/tmp)

I think that the line of code you referenced is probably okay. If the error says something about not being able to import python modules, then make sure that you remembered to include a requirements.txt and modify the setup_config.json accordingly. If the error says something about not being able to find model files, then make sure that you remembered to include the model files in the setup_config.json.

Hope this helps!

**Comment by sbsyangjian** [comment]
First, we put our project files including setup.py in the directory Our_Project 
We execute the cmd "cd Our_Project  && dynalabcli init -n t1"

Then we execute the STEP-4 of the tutorial "dynalab-cli test -n t1", the log print "Can not find the code ！"
Command:   dynalab-cli test -n t1
File: .dynalab/t1/setup_config.json
{
    "task": "flores_small1",
    "checkpoint": "upload_model/simple_model.pt",
    "handler": "handler.py",
    "requirements": false,
    "setup": true,
    "model_files": [],
    "exclude": []
}
I think it's because we don't create a "code" directory for the project.
The previous project encountering error can be listed as:
./Our_Project/
│
├── Project Files
└── setup.py
When we change the project path as below and we can build the docker successfully.
./Our_Project/
│
├── /code/Project Files && setup.py
└── Project Files

"""
In the docker file (dynalab/dynalab/dockerfiles/Dockerfile.dev), we notice
"RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e code; fi."
We think the code is not the module but the project folder where the setup.py locate
"""

**Comment by TristanThrush** [comment]
I think that the problem is that you need to do ```dynalab-cli init -n t1 --amend``` and modify setup_config.json in order to tell docker where your model code is.

```model_files``` should look something like ```["config.json", "pytorch_model.bin", "tokenizer_config.json", "spiece.model", "special_tokens_map.json"]```

**Comment by sbsyangjian** [comment]
Besides the .pt model file, we also use the sentencepiece and dict.txt. But we notice:
**Extra model files 2: If you do not want to flatten the file structure (e.g. there may be too many dependencies involved), you do not need to add them to the dynalab config. First of all, notice there is a ROOTPATH variable available in your handler template. **
Therefore, we do not specifically set the **model_files** but directly use the **ROOTPATH** to load the dict.txt and sentencepiece model file. 
There is the handler.py
`import json
import os
import sys
from omegaconf import DictConfig
import torch
from omegaconf import OmegaConf
from dynalab.handler.base_handler import BaseDynaHandler, ROOTPATH
from dynalab.tasks.flores_small1 import TaskIO
from dynalab.tasks import flores_small1
sys.path.append(ROOTPATH)
####################################
import ast
import fileinput
import logging
import math
import os
import sys
import time
from argparse import Namespace
from collections import namedtuple

import numpy as np
import torch
from fairseq import checkpoint_utils, distributed_utils, options, tasks, utils
from fairseq.data import encoders
from fairseq.dataclass.configs import FairseqConfig
from fairseq.dataclass.utils import convert_namespace_to_omegaconf
from fairseq.token_generation_constraints import pack_constraints, unpack_constraints
from fairseq_cli.generate import get_symbols_to_strip_from_output
############################################################################
LANG_CODE={
    'eng': 'en',
    'hrv': 'hr',
    'hun': 'hu',
    'srp': 'sr',
    'mkd': 'mk',
}

def encode_fn(x, bpe, tokenizer):
    if tokenizer is not None:
        x = tokenizer.encode(x)
    if bpe is not None:
        x = bpe.encode(x)
    return x


def decode_fn(x, bpe, tokenizer):
    if bpe is not None:
        x = bpe.decode(x)
    if tokenizer is not None:
        x = tokenizer.decode(x)
    return x


class Handler(BaseDynaHandler):
    def initialize(self, context):
        self.debug = True
        #context._system_properties['gpu_id'] = 0
        #print(context._system_properties)
        model_pt_path, model_file_dir, device_str = self._handler_initialize(context)
        self.taskIO = TaskIO()
        ##############################
        #parser = options.get_interactive_generation_parser()
        #args = options.parse_args_and_arch(parser)
        print("ROOTPATH: {}".format(ROOTPATH))
        self.cfg = Namespace()
        self.cfg.common = OmegaConf.create(...)
        self.cfg.task = Namespace(...)
        #self.cfg.task.lang_pairs = "en-hr,hr-en"
        self.cfg.generation = OmegaConf.create(...)
        self.cfg.common_eval = OmegaConf.create(...)
        self.task = tasks.setup_task(self.cfg.task)
        print(model_pt_path)
        print(model_file_dir)
        print(device_str)
        # Handle tokenization and BPE
        self.cfg.tokenizer = None
        self.cfg.bpe = OmegaConf.create({'_name': 'sentencepiece', 'sentencepiece_model': '{}/dict/sentencepiece.bpe.model'.format(ROOTPATH)})
        self.tokenizer = encoders.build_tokenizer(self.cfg.tokenizer)
        self.bpe = encoders.build_bpe(self.cfg.bpe)
        self.src_langtok_spec, self.tgt_langtok_spec = self.cfg.task.langtoks["main"]
        print("SPM: {}".format(self.bpe))
        self.models, _model_args = checkpoint_utils.load_model_ensemble(model_pt_path.split(), task=self.task)
        print("Model: {}".format(self.models))
        # Set dictionaries
        self.src_dict = self.task.source_dictionary
        self.tgt_dict = self.task.target_dictionary

        self.use_cuda = torch.cuda.is_available()
        print("Use_Cuda: {}".format(self.use_cuda))
        # Optimize ensemble for generation
        for model in self.models:
            if model is None:
                continue
            if self.cfg.common.fp16:
                model.half()
            if self.use_cuda:
                model.cuda()
            model.prepare_for_inference_(self.cfg)

        # Initialize generator
        self.generator = self.task.build_generator(self.models, self.cfg.generation)
        self.max_positions = utils.resolve_max_positions(
            self.task.max_positions(), *[model.max_positions() for model in self.models]
        )
        self.initialized = True


    def preprocess(self, data):
        """
        preprocess data into a format that the model can do inference on
        """
        example = self._read_data(data)

        # ############TODO 2: preprocess data #############
        uid = example["uid"]
        src_lang = example["sourceLanguage"]
        tgt_lang = example["targetLanguage"]
        # self.task.source_langs = [ LANG_CODE[src_lang] ]
        # self.task.target_langs = [ LANG_CODE[tgt_lang] ]
        self.task.args.source_lang = LANG_CODE[src_lang]
        self.task.args.target_lang = LANG_CODE[tgt_lang]
        src_str = example["sourceText"]
        #print(encode_fn(src_str, self.bpe, self.tokenizer))
        src_tokens = self.task.source_dictionary.encode_line(encode_fn(src_str, self.bpe, self.tokenizer), add_if_not_exist=False).long()[:self.max_positions[0] - 1]
        src_lang_tok = torch.LongTensor([self.task.data_manager.get_encoder_langtok(LANG_CODE[src_lang], LANG_CODE[tgt_lang], spec=self.src_langtok_spec)])
        src_tokens = torch.cat([src_lang_tok, src_tokens]).unsqueeze(0)
        src_lengths = torch.LongTensor([src_tokens.numel()])
        input_data = {
            "net_input": {
                "src_tokens": src_tokens.cuda() if self.use_cuda else src_tokens,
                "src_lengths": src_lengths.cuda() if self.use_cuda else src_lengths,
            },
            "src_str": src_str,
            "src_lang": src_lang,
            "tgt_lang": tgt_lang
        }
        #print(input_data)
        return input_data

    def inference(self, input_data):
        # ############TODO 3: inference ###################
        """
        Run model prediction using the processed data
        """
        hypos = self.task.inference_step(
            self.generator, self.models, input_data,
        )
        #print(len(hypos[0]))
        #exit()
        # #################################################
        for hypo in hypos[: min(len(hypos), self.cfg.generation.nbest)]:
            #print(hypo[0]['tokens'])
            #print(self.cfg.common_eval.post_process)
            hypo_tokens, hypo_str, alignment = utils.post_process_prediction(
                hypo_tokens=hypo[0]["tokens"].int().cpu(),
                src_str=input_data["src_str"],
                alignment=hypo[0]["alignment"],
                align_dict=None,
                tgt_dict=self.tgt_dict,
                remove_bpe=self.cfg.common_eval.post_process,
                extra_symbols_to_ignore=get_symbols_to_strip_from_output(self.generator),
            )
            inference_output = decode_fn(hypo_str, self.bpe, self.tokenizer)
            score = hypo[0]["score"] / math.log(2)  # convert to base 2
        return inference_output

    def postprocess(self, inference_output, data):
        response = dict()
        example = self._read_data(data)
        # ############TODO 4: postprocess response ########
        """
        Add attributes to response
        """
        response["id"] = example["uid"]
        response["translatedText"] = inference_output
        if self.debug:
            print(inference_output)
        # #################################################
        response = self.taskIO.sign_response(response, example)
        return [response]


_service = Handler()


def handle(data, context):
    if not _service.initialized:
        _service.initialize(context)
    if data is None:
        return None

    # ############TODO 5: assemble inference pipeline #####
    """
    Normally you don't need to change anything in this block.
    However, if you do need to change this part (e.g. function name, argument, etc.),
    remember to make corresponding changes in the Handler class definition.
    """
    input_data = _service.preprocess(data)
    output = _service.inference(input_data)
    response = _service.postprocess(output, data)
    # #####################################################

    return response`

**Comment by TristanThrush** [comment]
Thanks for letting me know that you are going down the ROOTPATH route; apologies for the misunderstanding! If you can get the docker to build and pass the test successfully by changing the project path, then you can always try uploading the model with this change. I'm not sure why it is necessary, though.

@mazhiyi @gwenzek let us know if you have advice about this.

**Comment by sbsyangjian** [comment]
Thanks for answering my question! Another question is that the total size needs to be less than 2GB when we execute the command "dynalab-cli upload -n t1". Does it mean the size of the model.pt < 2GB which we should ensure? We can not upload the model.pt with larger size ? Is there a way to commit a larger model there (>2GB)?

**Comment by gwenzek** [comment]
@sbsyangjian I don't think there is a hard limit at 2GB for uploading model. There is just a warning AFAIK, to prevent people accidentally submit big models. 
If the upload fail with the big model can you share with us the error message and then try this branch: #79  ?
I also saw errors when trying to upload big models, but they where on the client side.

**Comment by mazhiyi** [comment]
> I think the "RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e code; fi." should be "RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e .; fi."

This is correct. Will fix it. Thanks! 



2GB is a warning instead of a hard limit. Models bigger than 2GB are more likely to fail in deployment / evaluation.
