### ISSUE TITLE
Submission Limit Exceeded Warning: Provide Additional Details

### ISSUE THREAD

**Issue by maxbartolo** [facebookresearch/dynalab#83]
Submission Limit Exceeded Warning should state what the submission limit is, and when it will get reset

Also, minor bug report: the first time you try to upload a model when you've exceeded the submission limit, you get a warning such as `Failed to submit model electra-synqa due to submission limit exceeded`. If you try again, you will get `OverflowError: string longer than 2147483647 bytes`.

If you remove the tar.gz file from your root directory, you go back to the original submission limit warning (and if you try again after this, you will get the OverflowError again).

**Comment by mazhiyi** [comment]
Thanks for raising this Max!
> Also, minor bug report: the first time you try to upload a model when you've exceeded the submission limit, you get a warning such as Failed to submit model electra-synqa due to submission limit exceeded. If you try again, you will get OverflowError: string longer than 2147483647 bytes

This is a feature rather than a bug, since we keep the submitted `tar.gz` for people to inspect, and there is a prompt saying "you can inspect your submitted file at xxx.tar.gz" after submission. 

If we add a prompt after that saying "if you intend to re-submit, you should delete the tar.gz", would that make things easier? 


On additional details, how are we getting on with making limit task configurable? @TristanThrush ? Please assign the issue back when you are done with that.

**Comment by maxbartolo** [comment]
> This is a feature rather than a bug, since we keep the submitted tar.gz for people to inspect, and there is a prompt saying "you can inspect your submitted file at xxx.tar.gz" after submission.

Being able to inspect the submitted file is extremely useful, but I don't think its presence should affect re-submission. If so, we should have a check for the `.tar.gz` file and ask the user if they would like to remove it and proceed or cancel and review. It's almost worse in the case that the model size is too small to be caught by the `OverflowError` because then we could potentially be re-uploading old model submissions, right?

We could also consider keeping them in a separate directory (e.g. `previous_submissions`) inside root and renamed to something like `yyyymmdd-xxx.tar.gz` and excluding these from tar to prevent the error occurring, and then informing users that they currently have X previous submission files that they might want to review.

**Comment by TristanThrush** [comment]
https://github.com/facebookresearch/dynabench/pull/585

This should make throttling configurable for now

**Comment by mazhiyi** [comment]
For easier tracking, I've moved the feature request for better managing submitted files into a new issue #89, and closed this one as throttling error message.

**Comment by mazhiyi** [comment]
@maxbartolo Please pull the latest master and the the submission management should be ready.
