### ISSUE TITLE
Translate with ensemble models instead of one model

### ISSUE THREAD

**Issue by BaohaoLiao** [facebookresearch/dynalab#97]
Hi,
I take part in the wmt21 flores competition. I wonder is it possible for us to use an ensemble of multiple checkpoints instead of the best one? It is quite common for translation task. If yes, how could I do that? I use this [handler](https://github.com/facebookresearch/flores/blob/master/dynalab/handler.py) .  When I change line 287 to 
`manifest = {"model": {"serializedFile": "model1.pt:model2.pt"}}`, it didn't work.

**Comment by yingwaner** [comment]
Are we allowed to do model ensemble?

**Comment by gwenzek** [comment]
Yes, model ensemble are allowed, but you have the same memory/latency constraint than other models.
You'll need to adapt the `handler.py` code for several models, as well as the `setup_config.json` to list all model files.

**Comment by BaohaoLiao** [comment]
> Yes, model ensemble are allowed, but you have the same memory/latency constraint than other models.
> You'll need to adapt the `handler.py` code for several models, as well as the `setup_config.json` to list all model files.

Thanks, I will try it.
