### ISSUE TITLE
Showing "takendown" for my submission of flores task

### ISSUE THREAD

**Issue by BaohaoLiao** [facebookresearch/dynalab#98]
Hi,

I submitted a model (615M) (https://dynabench.org/models/247) to dynabench and it showed "takendown", could you check it for me? By the way, do you plan to improve dynabench so that it can output the error information?

Thank you in advance.

**Comment by yingwaner** [comment]
Hi, my submiision 249(https://dynabench.org/models/249) is also "takendown", could you check it for me? Thank you in advance.

**Comment by BaohaoLiao** [comment]
> Hi, my submiision 249(https://dynabench.org/models/249) is also "takendown", could you check it for me? Thank you in advance.

Hi, I change the batch size and it works. You could try.

**Comment by guzmanhe** [comment]
Can you look into: https://github.com/facebookresearch/dynalab/issues/96 and see if it addresses your problem?

**Comment by BaohaoLiao** [comment]
I solved this issue by decreasing the batch size. So I think it is caused by GPU memory limitation.
